[package]
name = "hwwasm-test-macros"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0.25"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
