name: report

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Tools
        run: sudo apt-get install -y texlive-latex-recommended latexmk biber
      - name: Build
        working-directory: report
        run: make
